# Site settings
title: Denise Grappein
email: denise.grappein@polito.it
url: https://dgrappein.github.io
description: "prova description"
keywords: "prova keywords"
skills: "This website is still under development"
meta_author: Denise Grappein

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: e7d5bd
  primary-rgb: "231,213,189"
  secondary: 800020
  secondary-dark: 2c3e50

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: ResearchGate
    url: https://www.researchgate.net/profile/Denise-Grappein

# Postal address (add as many lines as necessary)
address:
  - line: Corso Duca degli Abruzzi 24
  - line: 10129 Torino ITALY

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
